### ISSUE TITLE
Composite Name Generation [Feature Request!]

### ISSUE THREAD

**Issue by ghost** [madigan/ncounter-ng2#9]
**As a** DM
**I want** to be able to generate multi-part monster names, combing multiple lists into a single string/name, separated by a character of my choice (usually spaces or dashes).
**So that** I don't have to retype a name if I want multiple combinations of two words (such as "eats" and [body part]), and have a greater variety of names after only typing a few words (i.e. if I have a list of five colors, and another list of five kobold body parts, I have 25 new unique Kobold names (Cartesian product of the two sets)).

Acceptance Criteria

- [ ] When editing or creating monsters in Bestiary screen, multiple Name lists can be selected
- [x] When doing the above, the order in which the lists will be used is clear (e.g. this list will be used for the first part of the name, this part will be used for the second, this part for the third...)
- [ ] When adding these creatures on the Fight! screen, a check is done to ensure that the name generated from these 2+ lists has _not_ already been used for a creature in the fight (is this super hard? I don't wanna make your life super hard)
- [x] When editing or creating monsters in the Bestiary screen, name concatenation type can be chosen, i.e each name from the list separated by a space (in case I just want first name, last name), a dash (e.g. Walks-On-Clouds-In-Moonlight), or an empty string (in case I'm putting together Orc names, and want to concatenate bits like "Mu" and "gorg," "grog," or "blik", to get the unique names Mugorg, Mugrog, and Mublik, with minimal effort).

Elaboration:
Although a simple list of names to choose from is perfect for human and human-like characters/cultures, I often find myself creating multi-part names for monster races, such as "Red Foot" for a Kobold, or "Eats-Knuckles-At-Dawn" for a Ghoul. If I could have the name generator draw from two or more lists, this would generate unexpected names (adding more variety to the enemies), while also letting me make a HUGE amount of names from a small amount of nouns, verbs, and adjectives. Also, as the RPG continues, I grow fearful that I will run out of names to think of, and repeatedly name different monsters the same thing. This feature will help generate names my measly brain cannot.

An Addendum:
Writing this out, I realized this is a crapton of work. So, like, feel free to completely ignore this feature request. It's crazy how much you've done already, and I suppose if I got off by butt and got to work, I could probably either find or write a simple program that generates the Cartesian product of strings, and then just add the result as a new list.

**Comment by madigan** [comment]
I'd say enforcing unique names should be a separate feature (you may want folks from the roster to only be added once as well).

**Comment by madigan** [comment]
I've pushed out an initial version to the web- let me know what you think.
